### PR TITLE
Let modules in HGC trigger geometry know about HGC cells

### PR DESCRIPTION
**Pull request by lgray**
Please update corresponding code in the ongoing PR.

### CODE REVIEW

**Comment by lgray** [comment]
@jbsauvan hold on two seconds, making something more efficient

**Comment by lgray** [comment]
@jbsauvan merge when you are ready, good to go now.

**Comment by jbsauvan** [comment]
@lgray It's not enough to know the list of cells in the module. We need to know the list of cells in each trigger cell contained in the module.

**Comment by lgray** [comment]
@jbsauvan Ah, true, moment then.

**Comment by lgray** [comment]
@jbsauvan OK, this should serve your purposes. (somewhat inefficient right now but can revisit later)

**Comment by jbsauvan** [comment]
Thanks @lgray . Merging.

**Pull request merged**
